apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-documents
  namespace: claims-demo
  labels:
    app: claims-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp3-csi
