apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-documents
  namespace: multi-agents
  labels:
    app: multi-agents
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp3-csi
