apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: qwen-vl-7b
  namespace: multimodal-demo  # PLACEHOLDER: Change to your namespace
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: vLLM NVIDIA GPU ServingRuntime for KServe
    opendatahub.io/template-name: vllm-cuda-runtime-template
    openshift.io/display-name: vLLM NVIDIA GPU ServingRuntime for KServe
  labels:
    opendatahub.io/dashboard: "true"
spec:
  multiModel: false
  supportedModelFormats:
  - name: vLLM
    autoSelect: true
  containers:
  - name: kserve-container
    image: registry.redhat.io/rhaiis/vllm-cuda-rhel9@sha256:ad756c01ec99a99cc7d93401c41b8d92ca96fb1ab7c5262919d818f2be4f3768
    command:
    - python
    - -m
    - vllm.entrypoints.openai.api_server
    args:
    - --port=8080
    - --model=/mnt/models
    - --served-model-name={{.Name}}
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: HF_HOME
      value: /tmp/hf_home
  annotations:
    opendatahub.io/kserve-runtime: vllm
    prometheus.io/port: "8080"
    prometheus.io/path: /metrics
