# Llama Guard 3 1B InferenceService for TrustyAI Guardrails
# Based on existing llama-guard-3-1b from llama-serve namespace
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: guardrails-detector
  namespace: claims-demo
  labels:
    trustyai/detector: "true"  # CRITICAL: Label for GuardrailsOrchestrator auto-discovery
    app: claims-processing
    component: guardrails-detector
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
    openshift.io/display-name: "Claims Guardrails Detector (Llama Guard 3 1B)"
spec:
  predictor:
    automountServiceAccountToken: false
    minReplicas: 1
    maxReplicas: 1
    model:
      modelFormat:
        name: vLLM
      runtime: llama-guard-3-1b
      # Using OCI modelcar from Red Hat AI Services
      storageUri: oci://quay.io/rh-aiservices-bu/llama-guard-3-1b-modelcar:2.0.0
      resources:
        requests:
          cpu: "1"
          memory: 8Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: "8"
          memory: 10Gi
          nvidia.com/gpu: "1"
    tolerations:
      - effect: NoSchedule
        operator: Exists
