apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: claims-demo
  labels:
    helm.sh/chart: agentic-claims-demo-1.0.0
    app.kubernetes.io/name: agentic-claims-demo
    app.kubernetes.io/instance: agentic-claims-demo
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
    app: postgresql
type: Opaque
stringData:
  POSTGRES_ADMIN_PASSWORD: REPLACE_WITH_ADMIN_PASSWORD
  POSTGRES_DATABASE: claims_db
  POSTGRES_USER: claims_user
  POSTGRES_PASSWORD: REPLACE_WITH_PASSWORD
  LLAMASTACK_PASSWORD: null
  LLAMASTACK_DATABASE: llamastack
  LLAMASTACK_USER: llamastack
