apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  name: hibernate
  namespace: claims-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hibernate
subjects:
- kind: ServiceAccount
  name: hibernate
  namespace: claims-demo
