apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: multi-agents-check-deps
  namespace: multi-agents
  labels:
    helm.sh/chart: multi-agents-1.0.0
    app.kubernetes.io/name: multi-agents
    app.kubernetes.io/instance: multi-agents
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: llamastack-init
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: '-95'
    helm.sh/hook-delete-policy: before-hook-creation
    argocd.argoproj.io/sync-wave: '-95'
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - pods/exec
  verbs:
  - create
