apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '2'
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/runtime-version: v0.11.2
    opendatahub.io/serving-runtime-scope: global
    opendatahub.io/template-display-name: vLLM NVIDIA GPU ServingRuntime for KServe
    opendatahub.io/template-name: vllm-cuda-runtime-template
    openshift.io/display-name: vLLM NVIDIA GPU ServingRuntime for KServe
  labels:
    opendatahub.io/dashboard: 'true'
    helm.sh/chart: agentic-claims-demo-1.0.0
    app.kubernetes.io/name: agentic-claims-demo
    app.kubernetes.io/instance: agentic-claims-demo
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
  name: llama
  namespace: claims-demo
spec:
  annotations:
    opendatahub.io/kserve-runtime: vllm
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
  - name: kserve-container
    image: registry.redhat.io/rhaiis/vllm-cuda-rhel9:latest
    command:
    - python
    - -m
    - vllm.entrypoints.openai.api_server
    args:
    - --port=8080
    - --model=/mnt/models
    - --served-model-name={{.Name}}
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: HF_HOME
      value: /tmp/hf_home
  multiModel: false
  supportedModelFormats:
  - name: vLLM
    autoSelect: true
