apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: multi-agents
  labels:
    app: claims-processing
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: backend
