apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: multi-agents
  labels:
    app: frontend
    component: frontend
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: frontend
  type: ClusterIP
