apiVersion: v1
kind: Service
metadata:
  name: ocr-server
  namespace: multi-agents
  labels:
    helm.sh/chart: multi-agents-1.0.0
    app.kubernetes.io/name: multi-agents
    app.kubernetes.io/instance: multi-agents
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
    app: ocr-server
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: backend
