apiVersion: v1
kind: Service
metadata:
  name: ocr-server
  namespace: claims-demo
  labels:
    helm.sh/chart: agentic-claims-demo-1.0.0
    app.kubernetes.io/name: agentic-claims-demo
    app.kubernetes.io/instance: agentic-claims-demo
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
    app: ocr-server
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: backend
