apiVersion: v1
kind: Service
metadata:
  name: ocr-server
  namespace: claims-demo
  labels:
    app: ocr-server
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ocr-server
