apiVersion: v1
kind: Service
metadata:
  name: rag-server
  namespace: multi-agents
  labels:
    app: rag-server
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: rag-server
