apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama32-3b-instruct-model
  namespace: llama-instruct-32-3b-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
